### ISSUE TITLE
hi，which version of tensorflow should be used?

### ISSUE THREAD

**Issue by breezedeus** [pbhatia243/Neural_Conversation_Models#12]

**Comment by breezedeus** [comment]
I tried to run it at tf 1.0, but didn't succeed.

**Comment by hailiang-wang** [comment]
@breezedeus 
tensorflow-0.12.1

**Comment by hamedkhanpour** [comment]
I'm using tensorflow 1.2.0-rc2 but the program returns the following error:

File "......\my_seq2seq.py", line 48, in <module>
from tensorflow.python.ops.rnn_cell import _linear as linear
ImportError: cannot import name '_linear'

**Comment by bshao001** [comment]
@hamedkhanpour 
Try: 
from tensorflow.python.ops import rnn_cell_impl
linear = rnn_cell_impl._linear

**Comment by bshao001** [comment]
I am trying to incorporate my_seq2seq.py into my chatbot in tensorflow 1.2, and it does not work. My changes were involved, but still no luck.
