### ISSUE TITLE
Problem when trying the network

### ISSUE THREAD

**Issue by kushia** [pbhatia243/Neural_Conversation_Models#4]
Hi everyone,
I trained the model for a few epochs and tried to run it in interactive mode.
I used this command 
python neural_conversation_model.py --train_dir ubuntu/ --en_vocab_size 60000 --size 512 --data_path ubuntu/train.tsv --dev_data ubuntu/valid.tsv  --vocab_path ubuntu/60k_vocan.en --attention --decode --beam_search --beam_size 25

But I got this error 
    state_size =  int(initial_state.get_shape().with_rank(2)[1])
AttributeError: 'tuple' object has no attribute 'get_shape'

Do you have an idea why ?
Thanks!

**Comment by anutammewar** [comment]
I'm also getting the same error.
Maybe it is related to: https://github.com/tensorflow/tensorflow/issues/3056
If you figure out the solution, let me know.

**Comment by mengwenliu** [comment]
try using tensorflow-0.10.0rc0
You may want to look at this: https://github.com/tensorflow/tensorflow/issues/3056

**Comment by pbhatia243** [comment]
Updated with latest version.
